export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';

export const ORDER_BURGER_STARTED = 'ORDER_BURGER_STARTED';
export const ORDER_BURGER_SUCCEDED = 'ORDER_BURGER_SUCCEDED';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_INIT = 'ORDER_INIT';

export const FETCH_ORDERS_STARTED = 'FETCH_ORDERS_STARTED';
export const FETCH_ORDERS_SUCCEEDED = 'FETCH_ORDERS_SUCCEEDED';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';