export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';

export const INIT_ORDER = 'INIT_ORDER';
export const START_ORDER = 'START_ORDER';
export const ORDER_SUCCEEDED = 'ORDER_SUCCEEDED';
export const ORDER_FAILED = 'ORDER_FAILED';

export const START_FETCHING_ORDERS = 'START_FETCHING_ORDERS';
export const FETCH_ORDERS_SUCCEEDED = 'FETCH_ORDERS_SUCCEEDED';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH';